baseurl = "https://jiakevin.githugo.io"
languageCode = "en-us"
title = "Jia Kevin Hugo Site"
theme = "hello-friend-ng"

[params]
  dateform        = "Nov 23, 2019"
  dateformShort   = "Nov 23"
  dateformNum     = "2019-11-23"
  dateformNumTime = "2019-11-23 00:00 -0000"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Homepage and blog by Kevin Jia"
  keywords = "homepage, blog, science, informatics, development, programming, cs, java, spring, springboot, spring cloud"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Hello My Friends"
    subtitle = "Life is enlightenment"
    keywords = "java, spring, spring boot, spring cloud"
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Hello My Friends"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
